title: "Rushikesh Palnitkar"
description: "Data Engineer | AWS, Snowflake, Event-Driven ETL"
theme: minima

# Optional: show links in header (minima supports these)
github_username: rushikesh2842
linkedin_username: https://www.linkedin.com/in/rushikesh-palnitkar/
